name: hackathon-deployment
on:
  workflow_dispatch:
    inputs:
    
      resource_group:
        description: 'Resource Group'
        required: true
        default: 'hackathon-csa-west'

      azure_region:
        description: 'Azure Region'
        required: true
        default: 'eastus'




jobs:
  hackathon-deployment:
    runs-on: ubuntu-latest
    
    steps:
        # install azure-cli
      - uses: pietrobolcato/install-azure-cli-action@main
      
        # Login using Service Principal
      - name: AZ Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CLUSTER_SERVICE_PRINCIPAL }}

      - name: checkout repo
        uses: actions/checkout@v2
 
