name: hackathon-deployment
on:
  workflow_dispatch:
    inputs:
    
      resource_group:
        description: 'Resource Group'
        required: true
        default: 'hackathon-csa-west'

      azure_region:
        description: 'Azure Region'
        required: true
        default: 'eastus'




jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Service Principal Authentication
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
        
    - name: Run Az CLI script
      run: |
        az account show
    - name: Run Az PowerShell script
      run: |
        Get-AzContext
