name: hackathon-deployment
on:
  workflow_dispatch:
    inputs:
    
      resource_group:
        description: 'Resource Group'
        required: true
        default: 'hackathon-csa-west'

      azure_region:
        description: 'Azure Region'
        required: true
        default: 'eastus'




jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Login via Az module
      uses: azure/login@v1.4.3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true 
    - name: Run Az CLI script
      run: |
        az account show
    - name: Run Az PowerShell script
      run: |
        Get-AzContext
