name: hackathon-deployment
on:
  workflow_dispatch:
    inputs:
    
      resource_group:
        description: 'Resource Group'
        required: true
        default: 'hackathon-csa-west'

      azure_region:
        description: 'Azure Region'
        required: true
        default: 'eastus'




jobs:
  deploy-hackathon-code:
    runs-on: ubuntu-latest

    steps:
      - name: Az CLI login
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            az group list
